insert into teams (sport, external_id, name, abbreviation, logo_url, conference, division) values
  ('NFL', '22', 'Arizona Cardinals', 'ARI', 'https://a.espncdn.com/i/teamlogos/nfl/500/ari.png', 'NFC', 'West'),
  ('NFL', '1', 'Atlanta Falcons', 'ATL', 'https://a.espncdn.com/i/teamlogos/nfl/500/atl.png', 'NFC', 'South'),
  ('NFL', '33', 'Baltimore Ravens', 'BAL', 'https://a.espncdn.com/i/teamlogos/nfl/500/bal.png', 'AFC', 'North'),
  ('NFL', '2', 'Buffalo Bills', 'BUF', 'https://a.espncdn.com/i/teamlogos/nfl/500/buf.png', 'AFC', 'East'),
  ('NFL', '29', 'Carolina Panthers', 'CAR', 'https://a.espncdn.com/i/teamlogos/nfl/500/car.png', 'NFC', 'South'),
  ('NFL', '3', 'Chicago Bears', 'CHI', 'https://a.espncdn.com/i/teamlogos/nfl/500/chi.png', 'NFC', 'North'),
  ('NFL', '4', 'Cincinnati Bengals', 'CIN', 'https://a.espncdn.com/i/teamlogos/nfl/500/cin.png', 'AFC', 'North'),
  ('NFL', '5', 'Cleveland Browns', 'CLE', 'https://a.espncdn.com/i/teamlogos/nfl/500/cle.png', 'AFC', 'North'),
  ('NFL', '6', 'Dallas Cowboys', 'DAL', 'https://a.espncdn.com/i/teamlogos/nfl/500/dal.png', 'NFC', 'East'),
  ('NFL', '7', 'Denver Broncos', 'DEN', 'https://a.espncdn.com/i/teamlogos/nfl/500/den.png', 'AFC', 'West'),
  ('NFL', '8', 'Detroit Lions', 'DET', 'https://a.espncdn.com/i/teamlogos/nfl/500/det.png', 'NFC', 'North'),
  ('NFL', '9', 'Green Bay Packers', 'GB', 'https://a.espncdn.com/i/teamlogos/nfl/500/gb.png', 'NFC', 'North'),
  ('NFL', '34', 'Houston Texans', 'HOU', 'https://a.espncdn.com/i/teamlogos/nfl/500/hou.png', 'AFC', 'South'),
  ('NFL', '11', 'Indianapolis Colts', 'IND', 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png', 'AFC', 'South'),
  ('NFL', '30', 'Jacksonville Jaguars', 'JAX', 'https://a.espncdn.com/i/teamlogos/nfl/500/jax.png', 'AFC', 'South'),
  ('NFL', '12', 'Kansas City Chiefs', 'KC', 'https://a.espncdn.com/i/teamlogos/nfl/500/kc.png', 'AFC', 'West'),
  ('NFL', '24', 'Los Angeles Chargers', 'LAC', 'https://a.espncdn.com/i/teamlogos/nfl/500/lac.png', 'AFC', 'West'),
  ('NFL', '14', 'Los Angeles Rams', 'LAR', 'https://a.espncdn.com/i/teamlogos/nfl/500/lar.png', 'NFC', 'West'),
  ('NFL', '13', 'Las Vegas Raiders', 'LV', 'https://a.espncdn.com/i/teamlogos/nfl/500/lv.png', 'AFC', 'West'),
  ('NFL', '15', 'Miami Dolphins', 'MIA', 'https://a.espncdn.com/i/teamlogos/nfl/500/mia.png', 'AFC', 'East'),
  ('NFL', '16', 'Minnesota Vikings', 'MIN', 'https://a.espncdn.com/i/teamlogos/nfl/500/min.png', 'NFC', 'North'),
  ('NFL', '17', 'New England Patriots', 'NE', 'https://a.espncdn.com/i/teamlogos/nfl/500/ne.png', 'AFC', 'East'),
  ('NFL', '18', 'New Orleans Saints', 'NO', 'https://a.espncdn.com/i/teamlogos/nfl/500/no.png', 'NFC', 'South'),
  ('NFL', '19', 'New York Giants', 'NYG', 'https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png', 'NFC', 'East'),
  ('NFL', '20', 'New York Jets', 'NYJ', 'https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png', 'AFC', 'East'),
  ('NFL', '21', 'Philadelphia Eagles', 'PHI', 'https://a.espncdn.com/i/teamlogos/nfl/500/phi.png', 'NFC', 'East'),
  ('NFL', '23', 'Pittsburgh Steelers', 'PIT', 'https://a.espncdn.com/i/teamlogos/nfl/500/pit.png', 'AFC', 'North'),
  ('NFL', '26', 'Seattle Seahawks', 'SEA', 'https://a.espncdn.com/i/teamlogos/nfl/500/sea.png', 'NFC', 'West'),
  ('NFL', '25', 'San Francisco 49ers', 'SF', 'https://a.espncdn.com/i/teamlogos/nfl/500/sf.png', 'NFC', 'West'),
  ('NFL', '27', 'Tampa Bay Buccaneers', 'TB', 'https://a.espncdn.com/i/teamlogos/nfl/500/tb.png', 'NFC', 'South'),
  ('NFL', '10', 'Tennessee Titans', 'TEN', 'https://a.espncdn.com/i/teamlogos/nfl/500/ten.png', 'AFC', 'South'),
  ('NFL', '28', 'Washington Commanders', 'WSH', 'https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png', 'NFC', 'East');
